/*
AdventureWorks¡G
select top 100
SalesOrderNumber,
year(OrderDate) as OrderYear,
Month(OrderDate) as OrderMonth,
Day(OrderDate) as OrderDay,
CustomerID,
ContactID,
SalesPersonID,
TerritoryID,
SubTotal,
TaxAmt,
Freight,
TotalDue
from Sales.SalesOrderHeader t1 order by t1.CustomerID
*/
var data = {
    "Oltp1": {
        "Tables": [
            {
                "TableName": "Query1",
                "Columns": [
                    {
                        "ID": "SalesOrderNumber",
                        "ColumnName": "SalesOrderNumber",
                        "DataType": "string",
                        "Caption": "SalesOrderNumber"
                    },
                    {
                        "ID": "OrderYear",
                        "ColumnName": "OrderYear",
                        "DataType": "int",
                        "Caption": "OrderYear"
                    },
                    {
                        "ID": "OrderMonth",
                        "ColumnName": "OrderMonth",
                        "DataType": "int",
                        "Caption": "OrderMonth"
                    },
                    {
                        "ID": "OrderDay",
                        "ColumnName": "OrderDay",
                        "DataType": "int",
                        "Caption": "OrderDay"
                    },
                    {
                        "ID": "CustomerID",
                        "ColumnName": "CustomerID",
                        "DataType": "int",
                        "Caption": "CustomerID"
                    },
                    {
                        "ID": "ContactID",
                        "ColumnName": "ContactID",
                        "DataType": "int",
                        "Caption": "ContactID"
                    },
                    {
                        "ID": "SalesPersonID",
                        "ColumnName": "SalesPersonID",
                        "DataType": "int",
                        "Caption": "SalesPersonID"
                    },
                    {
                        "ID": "TerritoryID",
                        "ColumnName": "TerritoryID",
                        "DataType": "int",
                        "Caption": "TerritoryID"
                    },
                    {
                        "ID": "SubTotal",
                        "ColumnName": "SubTotal",
                        "DataType": "decimal",
                        "Caption": "SubTotal"
                    },
                    {
                        "ID": "TaxAmt",
                        "ColumnName": "TaxAmt",
                        "DataType": "decimal",
                        "Caption": "TaxAmt"
                    },
                    {
                        "ID": "Freight",
                        "ColumnName": "Freight",
                        "DataType": "decimal",
                        "Caption": "Freight"
                    },
                    {
                        "ID": "TotalDue",
                        "ColumnName": "TotalDue",
                        "DataType": "decimal",
                        "Caption": "TotalDue"
                    }
                ],
                "Rows": [
                    {
                        "SalesOrderNumber": "SO43860",
                        "OrderYear": 2001,
                        "OrderMonth": 8,
                        "OrderDay": 1,
                        "CustomerID": 1,
                        "ContactID": 322,
                        "SalesPersonID": 280,
                        "TerritoryID": 1,
                        "SubTotal": 13216.0537,
                        "TaxAmt": 1057.2843,
                        "Freight": 330.4013,
                        "TotalDue": 14603.7393
                    },
                    {
                        "SalesOrderNumber": "SO44501",
                        "OrderYear": 2001,
                        "OrderMonth": 11,
                        "OrderDay": 1,
                        "CustomerID": 1,
                        "ContactID": 322,
                        "SalesPersonID": 280,
                        "TerritoryID": 1,
                        "SubTotal": 23646.0339,
                        "TaxAmt": 1891.6827,
                        "Freight": 591.1508,
                        "TotalDue": 26128.8674
                    },
                    {
                        "SalesOrderNumber": "SO45283",
                        "OrderYear": 2002,
                        "OrderMonth": 2,
                        "OrderDay": 1,
                        "CustomerID": 1,
                        "ContactID": 322,
                        "SalesPersonID": 280,
                        "TerritoryID": 1,
                        "SubTotal": 34066.1881,
                        "TaxAmt": 2725.295,
                        "Freight": 851.6547,
                        "TotalDue": 37643.1378
                    },
                    {
                        "SalesOrderNumber": "SO46042",
                        "OrderYear": 2002,
                        "OrderMonth": 5,
                        "OrderDay": 1,
                        "CustomerID": 1,
                        "ContactID": 322,
                        "SalesPersonID": 280,
                        "TerritoryID": 1,
                        "SubTotal": 31423.5209,
                        "TaxAmt": 2513.8817,
                        "Freight": 785.588,
                        "TotalDue": 34722.9906
                    },
                    {
                        "SalesOrderNumber": "SO46976",
                        "OrderYear": 2002,
                        "OrderMonth": 8,
                        "OrderDay": 1,
                        "CustomerID": 2,
                        "ContactID": 369,
                        "SalesPersonID": 283,
                        "TerritoryID": 1,
                        "SubTotal": 9216.3596,
                        "TaxAmt": 737.3088,
                        "Freight": 230.409,
                        "TotalDue": 10184.0774
                    },
                    {
                        "SalesOrderNumber": "SO47997",
                        "OrderYear": 2002,
                        "OrderMonth": 11,
                        "OrderDay": 1,
                        "CustomerID": 2,
                        "ContactID": 369,
                        "SalesPersonID": 283,
                        "TerritoryID": 1,
                        "SubTotal": 4949.8589,
                        "TaxAmt": 395.9887,
                        "Freight": 123.7465,
                        "TotalDue": 5469.5941
                    },
                    {
                        "SalesOrderNumber": "SO49054",
                        "OrderYear": 2003,
                        "OrderMonth": 2,
                        "OrderDay": 1,
                        "CustomerID": 2,
                        "ContactID": 369,
                        "SalesPersonID": 283,
                        "TerritoryID": 1,
                        "SubTotal": 1574.1247,
                        "TaxAmt": 125.93,
                        "Freight": 39.3531,
                        "TotalDue": 1739.4078
                    },
                    {
                        "SalesOrderNumber": "SO50216",
                        "OrderYear": 2003,
                        "OrderMonth": 5,
                        "OrderDay": 1,
                        "CustomerID": 2,
                        "ContactID": 369,
                        "SalesPersonID": 283,
                        "TerritoryID": 1,
                        "SubTotal": 1751.5987,
                        "TaxAmt": 140.1279,
                        "Freight": 43.79,
                        "TotalDue": 1935.5166
                    },
                    {
                        "SalesOrderNumber": "SO51728",
                        "OrderYear": 2003,
                        "OrderMonth": 8,
                        "OrderDay": 1,
                        "CustomerID": 2,
                        "ContactID": 369,
                        "SalesPersonID": 283,
                        "TerritoryID": 1,
                        "SubTotal": 3534.1671,
                        "TaxAmt": 282.7334,
                        "Freight": 88.3542,
                        "TotalDue": 3905.2547
                    },
                    {
                        "SalesOrderNumber": "SO57044",
                        "OrderYear": 2003,
                        "OrderMonth": 11,
                        "OrderDay": 1,
                        "CustomerID": 2,
                        "ContactID": 369,
                        "SalesPersonID": 283,
                        "TerritoryID": 1,
                        "SubTotal": 4106.6501,
                        "TaxAmt": 328.532,
                        "Freight": 102.6663,
                        "TotalDue": 4537.8484
                    },
                    {
                        "SalesOrderNumber": "SO63198",
                        "OrderYear": 2004,
                        "OrderMonth": 2,
                        "OrderDay": 1,
                        "CustomerID": 2,
                        "ContactID": 369,
                        "SalesPersonID": 283,
                        "TerritoryID": 1,
                        "SubTotal": 3668.7336,
                        "TaxAmt": 293.4987,
                        "Freight": 91.7183,
                        "TotalDue": 4053.9506
                    },
                    {
                        "SalesOrderNumber": "SO69488",
                        "OrderYear": 2004,
                        "OrderMonth": 5,
                        "OrderDay": 1,
                        "CustomerID": 2,
                        "ContactID": 369,
                        "SalesPersonID": 283,
                        "TerritoryID": 1,
                        "SubTotal": 822.009,
                        "TaxAmt": 65.7607,
                        "Freight": 20.5502,
                        "TotalDue": 908.3199
                    },
                    {
                        "SalesOrderNumber": "SO44124",
                        "OrderYear": 2001,
                        "OrderMonth": 9,
                        "OrderDay": 1,
                        "CustomerID": 3,
                        "ContactID": 176,
                        "SalesPersonID": 277,
                        "TerritoryID": 4,
                        "SubTotal": 18555.8149,
                        "TaxAmt": 1484.4652,
                        "Freight": 463.8954,
                        "TotalDue": 20504.1755
                    },
                    {
                        "SalesOrderNumber": "SO44791",
                        "OrderYear": 2001,
                        "OrderMonth": 12,
                        "OrderDay": 1,
                        "CustomerID": 3,
                        "ContactID": 176,
                        "SalesPersonID": 277,
                        "TerritoryID": 4,
                        "SubTotal": 17419.6078,
                        "TaxAmt": 1393.5686,
                        "Freight": 435.4902,
                        "TotalDue": 19248.6666
                    },
                    {
                        "SalesOrderNumber": "SO45568",
                        "OrderYear": 2002,
                        "OrderMonth": 3,
                        "OrderDay": 1,
                        "CustomerID": 3,
                        "ContactID": 176,
                        "SalesPersonID": 277,
                        "TerritoryID": 4,
                        "SubTotal": 18285.6382,
                        "TaxAmt": 1462.8511,
                        "Freight": 457.141,
                        "TotalDue": 20205.6303
                    },
                    {
                        "SalesOrderNumber": "SO46377",
                        "OrderYear": 2002,
                        "OrderMonth": 6,
                        "OrderDay": 1,
                        "CustomerID": 3,
                        "ContactID": 176,
                        "SalesPersonID": 277,
                        "TerritoryID": 4,
                        "SubTotal": 11796.1804,
                        "TaxAmt": 943.6944,
                        "Freight": 294.9045,
                        "TotalDue": 13034.7793
                    },
                    {
                        "SalesOrderNumber": "SO47439",
                        "OrderYear": 2002,
                        "OrderMonth": 9,
                        "OrderDay": 1,
                        "CustomerID": 3,
                        "ContactID": 176,
                        "SalesPersonID": 277,
                        "TerritoryID": 4,
                        "SubTotal": 71112.1316,
                        "TaxAmt": 5688.9705,
                        "Freight": 1777.8033,
                        "TotalDue": 78578.9054
                    },
                    {
                        "SalesOrderNumber": "SO48378",
                        "OrderYear": 2002,
                        "OrderMonth": 12,
                        "OrderDay": 1,
                        "CustomerID": 3,
                        "ContactID": 176,
                        "SalesPersonID": 277,
                        "TerritoryID": 4,
                        "SubTotal": 51198.5404,
                        "TaxAmt": 4095.8832,
                        "Freight": 1279.9635,
                        "TotalDue": 56574.3871
                    },
                    {
                        "SalesOrderNumber": "SO49538",
                        "OrderYear": 2003,
                        "OrderMonth": 3,
                        "OrderDay": 1,
                        "CustomerID": 3,
                        "ContactID": 176,
                        "SalesPersonID": 275,
                        "TerritoryID": 4,
                        "SubTotal": 27899.9579,
                        "TaxAmt": 2231.9966,
                        "Freight": 697.4989,
                        "TotalDue": 30829.4534
                    },
                    {
                        "SalesOrderNumber": "SO50748",
                        "OrderYear": 2003,
                        "OrderMonth": 6,
                        "OrderDay": 1,
                        "CustomerID": 3,
                        "ContactID": 176,
                        "SalesPersonID": 275,
                        "TerritoryID": 4,
                        "SubTotal": 47138.0027,
                        "TaxAmt": 3771.0402,
                        "Freight": 1178.4501,
                        "TotalDue": 52087.493
                    },
                    {
                        "SalesOrderNumber": "SO53616",
                        "OrderYear": 2003,
                        "OrderMonth": 9,
                        "OrderDay": 1,
                        "CustomerID": 3,
                        "ContactID": 176,
                        "SalesPersonID": 275,
                        "TerritoryID": 4,
                        "SubTotal": 83436.1754,
                        "TaxAmt": 6674.894,
                        "Freight": 2085.9044,
                        "TotalDue": 92196.9738
                    },
                    {
                        "SalesOrderNumber": "SO59011",
                        "OrderYear": 2003,
                        "OrderMonth": 12,
                        "OrderDay": 1,
                        "CustomerID": 3,
                        "ContactID": 176,
                        "SalesPersonID": 275,
                        "TerritoryID": 4,
                        "SubTotal": 40109.0555,
                        "TaxAmt": 3208.7244,
                        "Freight": 1002.7264,
                        "TotalDue": 44320.5063
                    },
                    {
                        "SalesOrderNumber": "SO65310",
                        "OrderYear": 2004,
                        "OrderMonth": 3,
                        "OrderDay": 1,
                        "CustomerID": 3,
                        "ContactID": 176,
                        "SalesPersonID": 275,
                        "TerritoryID": 4,
                        "SubTotal": 15431.5196,
                        "TaxAmt": 1234.5216,
                        "Freight": 385.788,
                        "TotalDue": 17051.8292
                    },
                    {
                        "SalesOrderNumber": "SO71889",
                        "OrderYear": 2004,
                        "OrderMonth": 6,
                        "OrderDay": 1,
                        "CustomerID": 3,
                        "ContactID": 176,
                        "SalesPersonID": 275,
                        "TerritoryID": 4,
                        "SubTotal": 31559.7518,
                        "TaxAmt": 2524.7801,
                        "Freight": 788.9938,
                        "TotalDue": 34873.5257
                    },
                    {
                        "SalesOrderNumber": "SO46642",
                        "OrderYear": 2002,
                        "OrderMonth": 7,
                        "OrderDay": 1,
                        "CustomerID": 4,
                        "ContactID": 321,
                        "SalesPersonID": 277,
                        "TerritoryID": 4,
                        "SubTotal": 118394.1258,
                        "TaxAmt": 9471.5301,
                        "Freight": 2959.8531,
                        "TotalDue": 130825.509
                    },
                    {
                        "SalesOrderNumber": "SO47658",
                        "OrderYear": 2002,
                        "OrderMonth": 10,
                        "OrderDay": 1,
                        "CustomerID": 4,
                        "ContactID": 321,
                        "SalesPersonID": 277,
                        "TerritoryID": 4,
                        "SubTotal": 119637.8301,
                        "TaxAmt": 9571.0264,
                        "Freight": 2990.9458,
                        "TotalDue": 132199.8023
                    },
                    {
                        "SalesOrderNumber": "SO48740",
                        "OrderYear": 2003,
                        "OrderMonth": 1,
                        "OrderDay": 1,
                        "CustomerID": 4,
                        "ContactID": 321,
                        "SalesPersonID": 275,
                        "TerritoryID": 4,
                        "SubTotal": 97037.566,
                        "TaxAmt": 7763.0053,
                        "Freight": 2425.9392,
                        "TotalDue": 107226.5105
                    },
                    {
                        "SalesOrderNumber": "SO49821",
                        "OrderYear": 2003,
                        "OrderMonth": 4,
                        "OrderDay": 1,
                        "CustomerID": 4,
                        "ContactID": 321,
                        "SalesPersonID": 275,
                        "TerritoryID": 4,
                        "SubTotal": 94133.8413,
                        "TaxAmt": 7530.7073,
                        "Freight": 2353.346,
                        "TotalDue": 104017.8946
                    },
                    {
                        "SalesOrderNumber": "SO51122",
                        "OrderYear": 2003,
                        "OrderMonth": 7,
                        "OrderDay": 1,
                        "CustomerID": 4,
                        "ContactID": 321,
                        "SalesPersonID": 275,
                        "TerritoryID": 4,
                        "SubTotal": 73368.0931,
                        "TaxAmt": 5869.4474,
                        "Freight": 1834.2023,
                        "TotalDue": 81071.7428
                    },
                    {
                        "SalesOrderNumber": "SO55233",
                        "OrderYear": 2003,
                        "OrderMonth": 10,
                        "OrderDay": 1,
                        "CustomerID": 4,
                        "ContactID": 321,
                        "SalesPersonID": 275,
                        "TerritoryID": 4,
                        "SubTotal": 73455.3404,
                        "TaxAmt": 5876.4272,
                        "Freight": 1836.3835,
                        "TotalDue": 81168.1511
                    },
                    {
                        "SalesOrderNumber": "SO61193",
                        "OrderYear": 2004,
                        "OrderMonth": 1,
                        "OrderDay": 1,
                        "CustomerID": 4,
                        "ContactID": 321,
                        "SalesPersonID": 275,
                        "TerritoryID": 4,
                        "SubTotal": 67414.7924,
                        "TaxAmt": 5393.1834,
                        "Freight": 1685.3698,
                        "TotalDue": 74493.3456
                    },
                    {
                        "SalesOrderNumber": "SO67292",
                        "OrderYear": 2004,
                        "OrderMonth": 4,
                        "OrderDay": 1,
                        "CustomerID": 4,
                        "ContactID": 321,
                        "SalesPersonID": 275,
                        "TerritoryID": 4,
                        "SubTotal": 62472.63,
                        "TaxAmt": 4997.8104,
                        "Freight": 1561.8158,
                        "TotalDue": 69032.2562
                    },
                    {
                        "SalesOrderNumber": "SO47436",
                        "OrderYear": 2002,
                        "OrderMonth": 9,
                        "OrderDay": 1,
                        "CustomerID": 5,
                        "ContactID": 368,
                        "SalesPersonID": 281,
                        "TerritoryID": 4,
                        "SubTotal": 20720.6175,
                        "TaxAmt": 1657.6494,
                        "Freight": 518.0154,
                        "TotalDue": 22896.2823
                    },
                    {
                        "SalesOrderNumber": "SO48374",
                        "OrderYear": 2002,
                        "OrderMonth": 12,
                        "OrderDay": 1,
                        "CustomerID": 5,
                        "ContactID": 368,
                        "SalesPersonID": 281,
                        "TerritoryID": 4,
                        "SubTotal": 9479.102,
                        "TaxAmt": 758.3282,
                        "Freight": 236.9776,
                        "TotalDue": 10474.4078
                    },
                    {
                        "SalesOrderNumber": "SO49534",
                        "OrderYear": 2003,
                        "OrderMonth": 3,
                        "OrderDay": 1,
                        "CustomerID": 5,
                        "ContactID": 368,
                        "SalesPersonID": 281,
                        "TerritoryID": 4,
                        "SubTotal": 8456.292,
                        "TaxAmt": 676.5034,
                        "Freight": 211.4073,
                        "TotalDue": 9344.2027
                    },
                    {
                        "SalesOrderNumber": "SO50746",
                        "OrderYear": 2003,
                        "OrderMonth": 6,
                        "OrderDay": 1,
                        "CustomerID": 5,
                        "ContactID": 368,
                        "SalesPersonID": 281,
                        "TerritoryID": 4,
                        "SubTotal": 9134.6608,
                        "TaxAmt": 730.7729,
                        "Freight": 228.3665,
                        "TotalDue": 10093.8002
                    },
                    {
                        "SalesOrderNumber": "SO53607",
                        "OrderYear": 2003,
                        "OrderMonth": 9,
                        "OrderDay": 1,
                        "CustomerID": 5,
                        "ContactID": 368,
                        "SalesPersonID": 281,
                        "TerritoryID": 4,
                        "SubTotal": 18463.4533,
                        "TaxAmt": 1477.0763,
                        "Freight": 461.5863,
                        "TotalDue": 20402.1159
                    },
                    {
                        "SalesOrderNumber": "SO59014",
                        "OrderYear": 2003,
                        "OrderMonth": 12,
                        "OrderDay": 1,
                        "CustomerID": 5,
                        "ContactID": 368,
                        "SalesPersonID": 281,
                        "TerritoryID": 4,
                        "SubTotal": 18431.5666,
                        "TaxAmt": 1474.5253,
                        "Freight": 460.7892,
                        "TotalDue": 20366.8811
                    },
                    {
                        "SalesOrderNumber": "SO65307",
                        "OrderYear": 2004,
                        "OrderMonth": 3,
                        "OrderDay": 1,
                        "CustomerID": 5,
                        "ContactID": 368,
                        "SalesPersonID": 281,
                        "TerritoryID": 4,
                        "SubTotal": 7950.2303,
                        "TaxAmt": 636.0184,
                        "Freight": 198.7558,
                        "TotalDue": 8785.0045
                    },
                    {
                        "SalesOrderNumber": "SO71890",
                        "OrderYear": 2004,
                        "OrderMonth": 6,
                        "OrderDay": 1,
                        "CustomerID": 5,
                        "ContactID": 368,
                        "SalesPersonID": 281,
                        "TerritoryID": 4,
                        "SubTotal": 10729.5078,
                        "TaxAmt": 858.3606,
                        "Freight": 268.2377,
                        "TotalDue": 11856.1061
                    },
                    {
                        "SalesOrderNumber": "SO53596",
                        "OrderYear": 2003,
                        "OrderMonth": 9,
                        "OrderDay": 1,
                        "CustomerID": 6,
                        "ContactID": 177,
                        "SalesPersonID": 276,
                        "TerritoryID": 4,
                        "SubTotal": 59.9326,
                        "TaxAmt": 4.7946,
                        "Freight": 1.4983,
                        "TotalDue": 66.2255
                    },
                    {
                        "SalesOrderNumber": "SO59030",
                        "OrderYear": 2003,
                        "OrderMonth": 12,
                        "OrderDay": 1,
                        "CustomerID": 6,
                        "ContactID": 177,
                        "SalesPersonID": 276,
                        "TerritoryID": 4,
                        "SubTotal": 545.0322,
                        "TaxAmt": 43.6026,
                        "Freight": 13.6258,
                        "TotalDue": 602.2606
                    },
                    {
                        "SalesOrderNumber": "SO65287",
                        "OrderYear": 2004,
                        "OrderMonth": 3,
                        "OrderDay": 1,
                        "CustomerID": 6,
                        "ContactID": 177,
                        "SalesPersonID": 276,
                        "TerritoryID": 4,
                        "SubTotal": 559.0108,
                        "TaxAmt": 44.7209,
                        "Freight": 13.9753,
                        "TotalDue": 617.707
                    },
                    {
                        "SalesOrderNumber": "SO71915",
                        "OrderYear": 2004,
                        "OrderMonth": 6,
                        "OrderDay": 1,
                        "CustomerID": 6,
                        "ContactID": 177,
                        "SalesPersonID": 276,
                        "TerritoryID": 4,
                        "SubTotal": 2137.231,
                        "TaxAmt": 170.9785,
                        "Freight": 53.4308,
                        "TotalDue": 2361.6403
                    },
                    {
                        "SalesOrderNumber": "SO46613",
                        "OrderYear": 2002,
                        "OrderMonth": 7,
                        "OrderDay": 1,
                        "CustomerID": 7,
                        "ContactID": 320,
                        "SalesPersonID": 268,
                        "TerritoryID": 1,
                        "SubTotal": 3569.4338,
                        "TaxAmt": 285.5547,
                        "Freight": 89.2358,
                        "TotalDue": 3944.2243
                    },
                    {
                        "SalesOrderNumber": "SO47667",
                        "OrderYear": 2002,
                        "OrderMonth": 10,
                        "OrderDay": 1,
                        "CustomerID": 7,
                        "ContactID": 320,
                        "SalesPersonID": 276,
                        "TerritoryID": 1,
                        "SubTotal": 2449.6033,
                        "TaxAmt": 195.9683,
                        "Freight": 61.2401,
                        "TotalDue": 2706.8117
                    },
                    {
                        "SalesOrderNumber": "SO48765",
                        "OrderYear": 2003,
                        "OrderMonth": 1,
                        "OrderDay": 1,
                        "CustomerID": 7,
                        "ContactID": 320,
                        "SalesPersonID": 276,
                        "TerritoryID": 1,
                        "SubTotal": 1769.1174,
                        "TaxAmt": 141.5294,
                        "Freight": 44.2279,
                        "TotalDue": 1954.8747
                    },
                    {
                        "SalesOrderNumber": "SO49861",
                        "OrderYear": 2003,
                        "OrderMonth": 4,
                        "OrderDay": 1,
                        "CustomerID": 7,
                        "ContactID": 320,
                        "SalesPersonID": 276,
                        "TerritoryID": 1,
                        "SubTotal": 1596.2947,
                        "TaxAmt": 127.7036,
                        "Freight": 39.9074,
                        "TotalDue": 1763.9057
                    },
                    {
                        "SalesOrderNumber": "SO51874",
                        "OrderYear": 2003,
                        "OrderMonth": 8,
                        "OrderDay": 1,
                        "CustomerID": 8,
                        "ContactID": 367,
                        "SalesPersonID": 279,
                        "TerritoryID": 5,
                        "SubTotal": 8703.4707,
                        "TaxAmt": 696.2777,
                        "Freight": 217.5868,
                        "TotalDue": 9617.3352
                    },
                    {
                        "SalesOrderNumber": "SO57190",
                        "OrderYear": 2003,
                        "OrderMonth": 11,
                        "OrderDay": 1,
                        "CustomerID": 8,
                        "ContactID": 367,
                        "SalesPersonID": 279,
                        "TerritoryID": 5,
                        "SubTotal": 8888.6076,
                        "TaxAmt": 711.0886,
                        "Freight": 222.2152,
                        "TotalDue": 9821.9114
                    },
                    {
                        "SalesOrderNumber": "SO63220",
                        "OrderYear": 2004,
                        "OrderMonth": 2,
                        "OrderDay": 1,
                        "CustomerID": 8,
                        "ContactID": 367,
                        "SalesPersonID": 279,
                        "TerritoryID": 5,
                        "SubTotal": 5571.0288,
                        "TaxAmt": 445.6823,
                        "Freight": 139.2757,
                        "TotalDue": 6155.9868
                    },
                    {
                        "SalesOrderNumber": "SO69565",
                        "OrderYear": 2004,
                        "OrderMonth": 5,
                        "OrderDay": 1,
                        "CustomerID": 8,
                        "ContactID": 367,
                        "SalesPersonID": 279,
                        "TerritoryID": 5,
                        "SubTotal": 4293.256,
                        "TaxAmt": 343.4605,
                        "Freight": 107.3314,
                        "TotalDue": 4744.0479
                    },
                    {
                        "SalesOrderNumber": "SO48092",
                        "OrderYear": 2002,
                        "OrderMonth": 11,
                        "OrderDay": 1,
                        "CustomerID": 9,
                        "ContactID": 165,
                        "SalesPersonID": 279,
                        "TerritoryID": 5,
                        "SubTotal": 290.1614,
                        "TaxAmt": 23.2129,
                        "Freight": 7.254,
                        "TotalDue": 320.6283
                    },
                    {
                        "SalesOrderNumber": "SO49170",
                        "OrderYear": 2003,
                        "OrderMonth": 2,
                        "OrderDay": 1,
                        "CustomerID": 9,
                        "ContactID": 165,
                        "SalesPersonID": 279,
                        "TerritoryID": 5,
                        "SubTotal": 4903.775,
                        "TaxAmt": 392.302,
                        "Freight": 122.5944,
                        "TotalDue": 5418.6714
                    },
                    {
                        "SalesOrderNumber": "SO50234",
                        "OrderYear": 2003,
                        "OrderMonth": 5,
                        "OrderDay": 1,
                        "CustomerID": 9,
                        "ContactID": 165,
                        "SalesPersonID": 279,
                        "TerritoryID": 5,
                        "SubTotal": 586.989,
                        "TaxAmt": 46.9591,
                        "Freight": 14.6747,
                        "TotalDue": 648.6228
                    },
                    {
                        "SalesOrderNumber": "SO51758",
                        "OrderYear": 2003,
                        "OrderMonth": 8,
                        "OrderDay": 1,
                        "CustomerID": 9,
                        "ContactID": 165,
                        "SalesPersonID": 279,
                        "TerritoryID": 5,
                        "SubTotal": 1605.5854,
                        "TaxAmt": 128.4468,
                        "Freight": 40.1396,
                        "TotalDue": 1774.1718
                    },
                    {
                        "SalesOrderNumber": "SO57072",
                        "OrderYear": 2003,
                        "OrderMonth": 11,
                        "OrderDay": 1,
                        "CustomerID": 9,
                        "ContactID": 165,
                        "SalesPersonID": 279,
                        "TerritoryID": 5,
                        "SubTotal": 3221.8384,
                        "TaxAmt": 257.7471,
                        "Freight": 80.546,
                        "TotalDue": 3560.1315
                    },
                    {
                        "SalesOrderNumber": "SO63234",
                        "OrderYear": 2004,
                        "OrderMonth": 2,
                        "OrderDay": 1,
                        "CustomerID": 9,
                        "ContactID": 165,
                        "SalesPersonID": 279,
                        "TerritoryID": 5,
                        "SubTotal": 632.4859,
                        "TaxAmt": 50.5989,
                        "Freight": 15.8121,
                        "TotalDue": 698.8969
                    },
                    {
                        "SalesOrderNumber": "SO69452",
                        "OrderYear": 2004,
                        "OrderMonth": 5,
                        "OrderDay": 1,
                        "CustomerID": 9,
                        "ContactID": 165,
                        "SalesPersonID": 279,
                        "TerritoryID": 5,
                        "SubTotal": 4148.3876,
                        "TaxAmt": 331.871,
                        "Freight": 103.7097,
                        "TotalDue": 4583.9683
                    },
                    {
                        "SalesOrderNumber": "SO47411",
                        "OrderYear": 2002,
                        "OrderMonth": 9,
                        "OrderDay": 1,
                        "CustomerID": 10,
                        "ContactID": 319,
                        "SalesPersonID": 285,
                        "TerritoryID": 6,
                        "SubTotal": 45089.9298,
                        "TaxAmt": 3607.1944,
                        "Freight": 1127.2482,
                        "TotalDue": 49824.3724
                    },
                    {
                        "SalesOrderNumber": "SO48350",
                        "OrderYear": 2002,
                        "OrderMonth": 12,
                        "OrderDay": 1,
                        "CustomerID": 10,
                        "ContactID": 319,
                        "SalesPersonID": 285,
                        "TerritoryID": 6,
                        "SubTotal": 42422.9572,
                        "TaxAmt": 3393.8366,
                        "Freight": 1060.5739,
                        "TotalDue": 46877.3677
                    },
                    {
                        "SalesOrderNumber": "SO49467",
                        "OrderYear": 2003,
                        "OrderMonth": 3,
                        "OrderDay": 1,
                        "CustomerID": 10,
                        "ContactID": 319,
                        "SalesPersonID": 285,
                        "TerritoryID": 6,
                        "SubTotal": 45892.9666,
                        "TaxAmt": 3671.4373,
                        "Freight": 1147.3242,
                        "TotalDue": 50711.7281
                    },
                    {
                        "SalesOrderNumber": "SO50698",
                        "OrderYear": 2003,
                        "OrderMonth": 6,
                        "OrderDay": 1,
                        "CustomerID": 10,
                        "ContactID": 319,
                        "SalesPersonID": 285,
                        "TerritoryID": 6,
                        "SubTotal": 31903.3672,
                        "TaxAmt": 2552.2694,
                        "Freight": 797.5842,
                        "TotalDue": 35253.2208
                    },
                    {
                        "SalesOrderNumber": "SO53527",
                        "OrderYear": 2003,
                        "OrderMonth": 9,
                        "OrderDay": 1,
                        "CustomerID": 10,
                        "ContactID": 319,
                        "SalesPersonID": 285,
                        "TerritoryID": 6,
                        "SubTotal": 88901.8475,
                        "TaxAmt": 7112.1478,
                        "Freight": 2222.5462,
                        "TotalDue": 98236.5415
                    },
                    {
                        "SalesOrderNumber": "SO58972",
                        "OrderYear": 2003,
                        "OrderMonth": 12,
                        "OrderDay": 1,
                        "CustomerID": 10,
                        "ContactID": 319,
                        "SalesPersonID": 285,
                        "TerritoryID": 6,
                        "SubTotal": 97077.5808,
                        "TaxAmt": 7766.2065,
                        "Freight": 2426.9395,
                        "TotalDue": 107270.7268
                    },
                    {
                        "SalesOrderNumber": "SO65206",
                        "OrderYear": 2004,
                        "OrderMonth": 3,
                        "OrderDay": 1,
                        "CustomerID": 10,
                        "ContactID": 319,
                        "SalesPersonID": 285,
                        "TerritoryID": 6,
                        "SubTotal": 83047.2353,
                        "TaxAmt": 6643.7788,
                        "Freight": 2076.1809,
                        "TotalDue": 91767.195
                    },
                    {
                        "SalesOrderNumber": "SO71841",
                        "OrderYear": 2004,
                        "OrderMonth": 6,
                        "OrderDay": 1,
                        "CustomerID": 10,
                        "ContactID": 319,
                        "SalesPersonID": 285,
                        "TerritoryID": 6,
                        "SubTotal": 102044.1343,
                        "TaxAmt": 8163.5307,
                        "Freight": 2551.1034,
                        "TotalDue": 112758.7684
                    },
                    {
                        "SalesOrderNumber": "SO43853",
                        "OrderYear": 2001,
                        "OrderMonth": 8,
                        "OrderDay": 1,
                        "CustomerID": 11,
                        "ContactID": 366,
                        "SalesPersonID": 282,
                        "TerritoryID": 6,
                        "SubTotal": 31625.9064,
                        "TaxAmt": 2530.0725,
                        "Freight": 790.6477,
                        "TotalDue": 34946.6266
                    },
                    {
                        "SalesOrderNumber": "SO44495",
                        "OrderYear": 2001,
                        "OrderMonth": 11,
                        "OrderDay": 1,
                        "CustomerID": 11,
                        "ContactID": 366,
                        "SalesPersonID": 282,
                        "TerritoryID": 6,
                        "SubTotal": 4890.3356,
                        "TaxAmt": 391.2268,
                        "Freight": 122.2584,
                        "TotalDue": 5403.8208
                    },
                    {
                        "SalesOrderNumber": "SO45276",
                        "OrderYear": 2002,
                        "OrderMonth": 2,
                        "OrderDay": 1,
                        "CustomerID": 11,
                        "ContactID": 366,
                        "SalesPersonID": 282,
                        "TerritoryID": 6,
                        "SubTotal": 7307.9784,
                        "TaxAmt": 584.6383,
                        "Freight": 182.6995,
                        "TotalDue": 8075.3162
                    },
                    {
                        "SalesOrderNumber": "SO46035",
                        "OrderYear": 2002,
                        "OrderMonth": 5,
                        "OrderDay": 1,
                        "CustomerID": 11,
                        "ContactID": 366,
                        "SalesPersonID": 282,
                        "TerritoryID": 6,
                        "SubTotal": 14683.3568,
                        "TaxAmt": 1174.6685,
                        "Freight": 367.0839,
                        "TotalDue": 16225.1092
                    },
                    {
                        "SalesOrderNumber": "SO46953",
                        "OrderYear": 2002,
                        "OrderMonth": 8,
                        "OrderDay": 1,
                        "CustomerID": 12,
                        "ContactID": 166,
                        "SalesPersonID": 278,
                        "TerritoryID": 6,
                        "SubTotal": 79060.5774,
                        "TaxAmt": 6324.8462,
                        "Freight": 1976.5144,
                        "TotalDue": 87361.938
                    },
                    {
                        "SalesOrderNumber": "SO47980",
                        "OrderYear": 2002,
                        "OrderMonth": 11,
                        "OrderDay": 1,
                        "CustomerID": 12,
                        "ContactID": 166,
                        "SalesPersonID": 278,
                        "TerritoryID": 6,
                        "SubTotal": 27201.6262,
                        "TaxAmt": 2176.1301,
                        "Freight": 680.0407,
                        "TotalDue": 30057.797
                    },
                    {
                        "SalesOrderNumber": "SO49100",
                        "OrderYear": 2003,
                        "OrderMonth": 2,
                        "OrderDay": 1,
                        "CustomerID": 12,
                        "ContactID": 166,
                        "SalesPersonID": 278,
                        "TerritoryID": 6,
                        "SubTotal": 20749.6253,
                        "TaxAmt": 1659.97,
                        "Freight": 518.7406,
                        "TotalDue": 22928.3359
                    },
                    {
                        "SalesOrderNumber": "SO50203",
                        "OrderYear": 2003,
                        "OrderMonth": 5,
                        "OrderDay": 1,
                        "CustomerID": 12,
                        "ContactID": 166,
                        "SalesPersonID": 278,
                        "TerritoryID": 6,
                        "SubTotal": 48405.2778,
                        "TaxAmt": 3872.4222,
                        "Freight": 1210.1319,
                        "TotalDue": 53487.8319
                    },
                    {
                        "SalesOrderNumber": "SO51703",
                        "OrderYear": 2003,
                        "OrderMonth": 8,
                        "OrderDay": 1,
                        "CustomerID": 12,
                        "ContactID": 166,
                        "SalesPersonID": 278,
                        "TerritoryID": 6,
                        "SubTotal": 61466.1143,
                        "TaxAmt": 4917.2891,
                        "Freight": 1536.6529,
                        "TotalDue": 67920.0563
                    },
                    {
                        "SalesOrderNumber": "SO57023",
                        "OrderYear": 2003,
                        "OrderMonth": 11,
                        "OrderDay": 1,
                        "CustomerID": 12,
                        "ContactID": 166,
                        "SalesPersonID": 278,
                        "TerritoryID": 6,
                        "SubTotal": 42687.3909,
                        "TaxAmt": 3414.9913,
                        "Freight": 1067.1848,
                        "TotalDue": 47169.567
                    },
                    {
                        "SalesOrderNumber": "SO63141",
                        "OrderYear": 2004,
                        "OrderMonth": 2,
                        "OrderDay": 1,
                        "CustomerID": 12,
                        "ContactID": 166,
                        "SalesPersonID": 278,
                        "TerritoryID": 6,
                        "SubTotal": 4720.3618,
                        "TaxAmt": 377.6289,
                        "Freight": 118.009,
                        "TotalDue": 5215.9997
                    },
                    {
                        "SalesOrderNumber": "SO69401",
                        "OrderYear": 2004,
                        "OrderMonth": 5,
                        "OrderDay": 1,
                        "CustomerID": 12,
                        "ContactID": 166,
                        "SalesPersonID": 278,
                        "TerritoryID": 6,
                        "SubTotal": 21607.0277,
                        "TaxAmt": 1728.5622,
                        "Freight": 540.1757,
                        "TotalDue": 23875.7656
                    },
                    {
                        "SalesOrderNumber": "SO53608",
                        "OrderYear": 2003,
                        "OrderMonth": 9,
                        "OrderDay": 1,
                        "CustomerID": 14,
                        "ContactID": 365,
                        "SalesPersonID": 289,
                        "TerritoryID": 8,
                        "SubTotal": 2091.01,
                        "TaxAmt": 167.2808,
                        "Freight": 52.2753,
                        "TotalDue": 2310.5661
                    },
                    {
                        "SalesOrderNumber": "SO53609",
                        "OrderYear": 2003,
                        "OrderMonth": 9,
                        "OrderDay": 1,
                        "CustomerID": 14,
                        "ContactID": 365,
                        "SalesPersonID": 289,
                        "TerritoryID": 8,
                        "SubTotal": 3188.7342,
                        "TaxAmt": 255.0987,
                        "Freight": 79.7184,
                        "TotalDue": 3523.5513
                    },
                    {
                        "SalesOrderNumber": "SO59033",
                        "OrderYear": 2003,
                        "OrderMonth": 12,
                        "OrderDay": 1,
                        "CustomerID": 14,
                        "ContactID": 365,
                        "SalesPersonID": 289,
                        "TerritoryID": 8,
                        "SubTotal": 967.822,
                        "TaxAmt": 77.4258,
                        "Freight": 24.1956,
                        "TotalDue": 1069.4434
                    },
                    {
                        "SalesOrderNumber": "SO59053",
                        "OrderYear": 2003,
                        "OrderMonth": 12,
                        "OrderDay": 1,
                        "CustomerID": 14,
                        "ContactID": 365,
                        "SalesPersonID": 289,
                        "TerritoryID": 8,
                        "SubTotal": 402.222,
                        "TaxAmt": 32.1778,
                        "Freight": 10.0556,
                        "TotalDue": 444.4554
                    },
                    {
                        "SalesOrderNumber": "SO65090",
                        "OrderYear": 2004,
                        "OrderMonth": 2,
                        "OrderDay": 29,
                        "CustomerID": 14,
                        "ContactID": 365,
                        "SalesPersonID": 289,
                        "TerritoryID": 8,
                        "SubTotal": 98.774,
                        "TaxAmt": 7.9019,
                        "Freight": 2.4694,
                        "TotalDue": 109.1453
                    },
                    {
                        "SalesOrderNumber": "SO65305",
                        "OrderYear": 2004,
                        "OrderMonth": 3,
                        "OrderDay": 1,
                        "CustomerID": 14,
                        "ContactID": 365,
                        "SalesPersonID": 289,
                        "TerritoryID": 8,
                        "SubTotal": 318.4545,
                        "TaxAmt": 25.4764,
                        "Freight": 7.9614,
                        "TotalDue": 351.8923
                    },
                    {
                        "SalesOrderNumber": "SO71692",
                        "OrderYear": 2004,
                        "OrderMonth": 5,
                        "OrderDay": 31,
                        "CustomerID": 14,
                        "ContactID": 365,
                        "SalesPersonID": 289,
                        "TerritoryID": 8,
                        "SubTotal": 197.548,
                        "TaxAmt": 15.8038,
                        "Freight": 4.9387,
                        "TotalDue": 218.2905
                    },
                    {
                        "SalesOrderNumber": "SO71910",
                        "OrderYear": 2004,
                        "OrderMonth": 6,
                        "OrderDay": 1,
                        "CustomerID": 14,
                        "ContactID": 365,
                        "SalesPersonID": 289,
                        "TerritoryID": 8,
                        "SubTotal": 694.4405,
                        "TaxAmt": 55.5552,
                        "Freight": 17.361,
                        "TotalDue": 767.3567
                    },
                    {
                        "SalesOrderNumber": "SO53566",
                        "OrderYear": 2003,
                        "OrderMonth": 9,
                        "OrderDay": 1,
                        "CustomerID": 15,
                        "ContactID": 167,
                        "SalesPersonID": 290,
                        "TerritoryID": 9,
                        "SubTotal": 76765.5159,
                        "TaxAmt": 6141.2413,
                        "Freight": 1919.1379,
                        "TotalDue": 84825.8951
                    },
                    {
                        "SalesOrderNumber": "SO59018",
                        "OrderYear": 2003,
                        "OrderMonth": 12,
                        "OrderDay": 1,
                        "CustomerID": 15,
                        "ContactID": 167,
                        "SalesPersonID": 290,
                        "TerritoryID": 9,
                        "SubTotal": 48415.5983,
                        "TaxAmt": 3873.2479,
                        "Freight": 1210.39,
                        "TotalDue": 53499.2362
                    },
                    {
                        "SalesOrderNumber": "SO65273",
                        "OrderYear": 2004,
                        "OrderMonth": 3,
                        "OrderDay": 1,
                        "CustomerID": 15,
                        "ContactID": 167,
                        "SalesPersonID": 290,
                        "TerritoryID": 9,
                        "SubTotal": 15777.1566,
                        "TaxAmt": 1262.1725,
                        "Freight": 394.4289,
                        "TotalDue": 17433.758
                    },
                    {
                        "SalesOrderNumber": "SO71933",
                        "OrderYear": 2004,
                        "OrderMonth": 6,
                        "OrderDay": 1,
                        "CustomerID": 15,
                        "ContactID": 167,
                        "SalesPersonID": 290,
                        "TerritoryID": 9,
                        "SubTotal": 35092.7264,
                        "TaxAmt": 2807.4181,
                        "Freight": 877.3182,
                        "TotalDue": 38777.4627
                    },
                    {
                        "SalesOrderNumber": "SO47447",
                        "OrderYear": 2002,
                        "OrderMonth": 9,
                        "OrderDay": 1,
                        "CustomerID": 16,
                        "ContactID": 71,
                        "SalesPersonID": 282,
                        "TerritoryID": 10,
                        "SubTotal": 68272.1366,
                        "TaxAmt": 5461.7709,
                        "Freight": 1706.8034,
                        "TotalDue": 75440.7109
                    },
                    {
                        "SalesOrderNumber": "SO48386",
                        "OrderYear": 2002,
                        "OrderMonth": 12,
                        "OrderDay": 1,
                        "CustomerID": 16,
                        "ContactID": 71,
                        "SalesPersonID": 282,
                        "TerritoryID": 10,
                        "SubTotal": 61719.8811,
                        "TaxAmt": 4937.5905,
                        "Freight": 1542.997,
                        "TotalDue": 68200.4686
                    },
                    {
                        "SalesOrderNumber": "SO49510",
                        "OrderYear": 2003,
                        "OrderMonth": 3,
                        "OrderDay": 1,
                        "CustomerID": 16,
                        "ContactID": 71,
                        "SalesPersonID": 282,
                        "TerritoryID": 10,
                        "SubTotal": 56471.7759,
                        "TaxAmt": 4517.7421,
                        "Freight": 1411.7944,
                        "TotalDue": 62401.3124
                    },
                    {
                        "SalesOrderNumber": "SO50722",
                        "OrderYear": 2003,
                        "OrderMonth": 6,
                        "OrderDay": 1,
                        "CustomerID": 16,
                        "ContactID": 71,
                        "SalesPersonID": 284,
                        "TerritoryID": 10,
                        "SubTotal": 59855.1036,
                        "TaxAmt": 4788.4083,
                        "Freight": 1496.3776,
                        "TotalDue": 66139.8895
                    },
                    {
                        "SalesOrderNumber": "SO53562",
                        "OrderYear": 2003,
                        "OrderMonth": 9,
                        "OrderDay": 1,
                        "CustomerID": 16,
                        "ContactID": 71,
                        "SalesPersonID": 282,
                        "TerritoryID": 10,
                        "SubTotal": 97700.8284,
                        "TaxAmt": 7816.0663,
                        "Freight": 2442.5207,
                        "TotalDue": 107959.4154
                    },
                    {
                        "SalesOrderNumber": "SO59063",
                        "OrderYear": 2003,
                        "OrderMonth": 12,
                        "OrderDay": 1,
                        "CustomerID": 16,
                        "ContactID": 71,
                        "SalesPersonID": 282,
                        "TerritoryID": 10,
                        "SubTotal": 69085.5642,
                        "TaxAmt": 5526.8451,
                        "Freight": 1727.1391,
                        "TotalDue": 76339.5484
                    },
                    {
                        "SalesOrderNumber": "SO65271",
                        "OrderYear": 2004,
                        "OrderMonth": 3,
                        "OrderDay": 1,
                        "CustomerID": 16,
                        "ContactID": 71,
                        "SalesPersonID": 282,
                        "TerritoryID": 10,
                        "SubTotal": 66802.886,
                        "TaxAmt": 5344.2309,
                        "Freight": 1670.0722,
                        "TotalDue": 73817.1891
                    },
                    {
                        "SalesOrderNumber": "SO71938",
                        "OrderYear": 2004,
                        "OrderMonth": 6,
                        "OrderDay": 1,
                        "CustomerID": 16,
                        "ContactID": 71,
                        "SalesPersonID": 282,
                        "TerritoryID": 10,
                        "SubTotal": 88812.8625,
                        "TaxAmt": 7105.029,
                        "Freight": 2220.3216,
                        "TotalDue": 98138.2131
                    },
                    {
                        "SalesOrderNumber": "SO43676",
                        "OrderYear": 2001,
                        "OrderMonth": 7,
                        "OrderDay": 1,
                        "CustomerID": 17,
                        "ContactID": 364,
                        "SalesPersonID": 275,
                        "TerritoryID": 5,
                        "SubTotal": 17040.8246,
                        "TaxAmt": 1363.266,
                        "Freight": 426.0206,
                        "TotalDue": 18830.1112
                    }
                ]
            }
        ]
    }
}